future4code/Alves-landing-page5

index.html

commit inicial do esqueleto

---

index.html

Alteração item 2

---

index.html

commit inicial do esqueleto 2

---

index.html

alteração item 3

---

style.css

Adicionado esqueleto do CSS

---

index.css
index.html
quem-somos.css
quem_somos.html

commit do quem somos

---

index.css
index.html

Criação da Main com colunas e imagens

---

index.html
login.css
login.html
recuperar-senha.css
recuperar-senha.html
registrar.css
registrar.html

commit da autenticacao

---

index.html

adicinei em quem-somos.html

---

quem-somos.css
quem-somos.html

commit do rodape

---

quem-somos.html

Corrigi as cores dos icones e removi o quem somos da aba quem somos

---

index.css
index.html

Ajustes de responsividade da index

---

index.css
index.html

Finalização do Index

---

faq.css
login.css
login.html
recuperar-senha.css
registrar.css

Evandro responsividade autenticacao

---

faq.css

commit da responsividade do faq

---

quem-somos.css
quem-somos.html

finalização responsividade quem somos

---

faq.css
faq.html
index.css
login.html
quem-somos.css
quem-somos.html
recuperar-senha.html
registrar.html

commit de algumas correções de links

---

README.md

Evandro readme2

---

README.md

Evandro readme3

---

fazer-pedido.css
fazer-pedido.html

Adicionado overflow na aba fazer pedido

---

index.css

Ajustes de responsividade telas

---

README.md

commit do readme4

---

faq.css
quem-somos.css
quem-somos.html

Olavo ajuste respon quem somos 1280ppx
